Repository 28StoneConsulting/design-system, pull requests merged in 2021-03, with the labels that each got.

#24 White body color for global CSS. Removed component selectors from But…
  src/components/Button/Button.tsx
  src/shared/theme.ts
Labels: patch

#27 added Select and Switch stories
  src/material-ui-stories/Select.stories.tsx
  src/material-ui-stories/Switch.stories.tsx
  src/material-ui-stories/TextField.stories.tsx
Labels: skip-release

#33 Intro, Color and Typography pages. Theme enhancements.
  .storybook/main.js
  .storybook/preview-head.html
  public/index.html
  src/docs/Color.stories.mdx
  src/docs/Intro.stories.mdx
  src/docs/Typography.stories.mdx
  src/material-ui-stories/Progress.stories.tsx
  src/shared/theme.ts
Labels: minor

#32 Changed Tab indicator to white
  src/shared/theme.ts
Labels: patch

#34 Feature/dark mode
  .storybook/decorators/with-theme.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/theme.js
  docs/asset-manifest.json
  docs/iframe.html
  docs/index.html
  docs/main.887ebb38516f3d13c3b9.bundle.js
  docs/main.91b1959298003f1134c8.bundle.js
  docs/main.a7b28496cfeb63b9b4d9.bundle.js
  docs/main.a7b28496cfeb63b9b4d9.bundle.js.map
  docs/main.d14eaba713369b08a8f7.bundle.js
  docs/main.d14eaba713369b08a8f7.bundle.js.map
  docs/runtime~main.a7b28496cfeb63b9b4d9.bundle.js.map
  docs/runtime~main.d14eaba713369b08a8f7.bundle.js
  docs/runtime~main.d14eaba713369b08a8f7.bundle.js.map
  docs/static/media/logo-white.49fc678a.svg
  docs/vendors~main.988892ba78cab62b4a51.bundle.js
  docs/vendors~main.a7b28496cfeb63b9b4d9.bundle.js
  docs/vendors~main.a7b28496cfeb63b9b4d9.bundle.js.map
  docs/vendors~main.d14eaba713369b08a8f7.bundle.js
  docs/vendors~main.d14eaba713369b08a8f7.bundle.js.LICENSE.txt
  docs/vendors~main.d14eaba713369b08a8f7.bundle.js.map
  docs/vendors~main.fa0b08b3d28aa0abdd02.bundle.js
  docs/vendors~main.fa0b08b3d28aa0abdd02.bundle.js.LICENSE.txt
  package.json
  src/components/Link/Link.test.tsx
  src/docs/Color.stories.mdx
  src/docs/Typography.stories.mdx
  src/emotion.d.ts
  src/index.ts
  src/shared/theme.ts
  yarn.lock
Labels: major

#36 added wrappers
  src/material-ui-stories/Button.stories.tsx
  src/material-ui-stories/ButtonGroup.stories.tsx
  src/material-ui-stories/Checkbox.stories.tsx
  src/material-ui-stories/Chip.stories.tsx
  src/material-ui-stories/DatePicker.stories.tsx
  src/material-ui-stories/FloatingButton.stories.tsx
  src/material-ui-stories/Progress.stories.tsx
  src/material-ui-stories/Radio.stories.tsx
  src/material-ui-stories/Select.stories.tsx
  src/material-ui-stories/Switch.stories.tsx
  src/material-ui-stories/TextField.stories.tsx
Labels: skip-release
